import './globals.css'
import type { Metadata } from 'next'
import { Alegreya } from 'next/font/google'
import Image from 'next/image'
import FooterTier from '../public/FooterTier.svg'
import Hamburger from '../public/hamburger.svg'
const alegreya = Alegreya({ subsets: ['latin'] })
import Header from '@/components/Header'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={alegreya.className}>
      <body>
        {/* <div className="flex items-center justify-start lg:justify-evenly py-2 font-bold text-2xl fixed w-screen bg-white z-10">
          <div className="hidden md:block basis-1/2 flex-shrink">
            Frank Alvarez
          </div>
          <div className="md:hidden m-3 ml-6 flex-shrink-0 flex-grow">
            <Image alt="" src={Hamburger} className=""></Image>
          </div>
          <button className="md:hidden px-4 py-1 rounded-md bg-gray-800 text-white text-base mr-8">
            Download Resume
          </button>
          <div className="hidden md:block basis-1/3 flex-shrink-0">
            <div className="flex justify-evenly text-base ">
              <button>About</button>
              <button>My Skills</button>
              <button>Experience</button>
              <button>Contact Me</button>
            </div>
          </div>
        </div> */}
        <Header></Header>
        {children}
        <div></div>
        <footer className="h-5 w-full border-black border-y-4 overflow-y-visible overflow-x-clip">
          <Image
            src={FooterTier}
            className="relative align-bottom -top-[500px] min-w-[1200px] max-w-full w-full"
            alt=""
          />
        </footer>
      </body>
    </html>
  )
}
